tibco:
  url: "tcp://localhost:7233"
  user: rixon
  password: tibco
server:
  port: 9898
info:
  name: Tibco EMS Sample Application
  description: Tibco EMS Sample Application
spring:
  jta:
    transaction-manager-id: messaging-tryouts-tx
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      client-id: messaging-tryouts
    consumer:
      group-id: contract_consumers

management:
  health:
    jms:
      enabled: true
    db:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      client-id: messaging-tryouts
    consumer:
      group-id: contract_consumers

---
spring:
  config:
    activate:
      on-profile: rixmacmini2011
  kafka:
    bootstrap-servers: rixmacmini2011:9092
    admin:
      client-id: messaging-tryouts-rixmacmini2011
    consumer:
      group-id: contract_consumers_rixmacmini2011

management:
  health:
    jms:
      enabled: false
